# File: src\docker\Dockerfile_frontend

FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN streamlit --version

COPY src ./src

ENV PYTHONPATH=/app/src:$PYTHONPATH

EXPOSE 8501

CMD ["streamlit", "run", "src/frontend/app.py"]